### PR TITLE
New Maintainer / Exporting angular-load as Module

### PR DESCRIPTION
**Pull request by cseale**
https://github.com/urish/angular-load/issues/39

Hi @urish. My company is just starting using your library, but as you are looking for a new maintainer, I would like to take this on. My request includes a bit of retooling. 

*Main Features of PR* 

- `webpack`for bundling and modules.
- `jest` because it requires zero config.
- `eslint` because it is a more modern version of jshint
- `babel` because I want to update this to ES6 at some point

I figure if I will maintain this, I will switch the tools to the ones I use regularly!

*TODOS:*
 
- [x] Support Bower Installs
- [x] Support `<script>` install
- [x] Support NPM Install
- [x] Add Coverage
- [x] Add Travis CI
- [x] Add Minified Build

I will need some help with what's required by the Travis CI build and what I will need to continue publishing under npm and bower

### CODE REVIEW

**Comment by cseale** [comment]
@urish v0.4.2 is ready to be published

**Comment by urish** [comment]
Awesome @cseale !

I think it will make more sense to publish it as 0.5.0 (or perhaps even 1.0.0-rc.0), as this release will have some breaking changes (like moving `angular-load.js` to live inside `dist`).

Also, I see that you don't publish index.js to npm (only the `dist`) directory - is that on purpose?

**Comment by cseale** [comment]
`1.0.0-rc.0` makes sense. I originally left out the `index.js` because the webpack build produces the required UMD modules in `dist` and therefore the original scripts are not needed. But now thinking maybe to support older users, I should probably still include the pre-built `angular-load.js` script.

You might have stronger feelings about this. I would have never supported libraries for wide use quite like this before, what I am proposing to distribute might be a bit selfish

**Comment by urish** [comment]
What is your npm user name? I will add you as an owner for the package.

I suggest publishing as 1.0.0-rc.0, and marking as beta (i.e. `npm publish --tag beta`, and then after a week or so publish 1.0.0-rc.1 without the beta tag. This way, you will be able to get some feedback from early adopters before everybody migrates to the new release.

**Comment by cseale** [comment]
npm username is `cseale`

**Comment by urish** [comment]
great! I added you as an owner to the project:

    C:\P\angular-load>npm owner add cseale
    + cseale (angular-load)

**Pull request merged**
