### PR TITLE
Make sure onreadystatechange callback is only fired when file is fully loaded

### PR DESCRIPTION
**Pull request by davidchin**
In newer versions of IE, both `onreadystatechange` and `onload` callback gets fired (I assume `onreadystatechange` is there for backward compatibility). When `onreadystatechange` gets fired, we should check the state of the event, and only resolve the returned promise if `readyState` is `'complete'`.

### CODE REVIEW

**Comment by urish** [comment]
Thanks!

**Comment by davidchin** [comment]
Thanks @urish, is it possible for you to bump up the version?

**Comment by urish** [comment]
Yes, will be done shortly

**Comment by urish** [comment]
Released as 0.4.0

**Pull request merged**
