### PR TITLE
Use $q as a constructor.

### PR DESCRIPTION
**Pull request by realityking**
Note: This breaks compatability with Angular 1.2 and older. If that's not desiderable, just ignore this ;)

### CODE REVIEW

**Comment by realityking** [comment]
I've rebased the branch onto master to account for #19.

**Comment by realityking** [comment]
Any feedback on this?

**Comment by urish** [comment]
Sorry for not replying before :)

I'd rather keep compatible with Angular 1.2 unless there is a good reason not to... Do you see a very good reason to switch to this syntax?

Thanks!

**Comment by realityking** [comment]
Nope, it's only a minor improvement. Just wanted to try ;)

**Comment by urish** [comment]
Great, thank you for your time!

**Pull request closed without merging**
