### PR TITLE
Added IE8 support to script loading

### PR DESCRIPTION
**Pull request by benmarch**
I know you aren't supporting IE8, but this addition adds support as well as fixes inconsistent behavior in IE9 and 10. In IE10 we noticed that on the first page load this script would fail (callback wouldn't execute) but every page load thereafter worked fine. This change seems to make it work consistently, although I can't really explain why :) It would be really helpful for us if you could include this patch. 

Thanks!
Ben

### CODE REVIEW

**Comment by urish** [comment]
Looks good, thanks!

**Comment by benmarch** [comment]
Thank you for the incredibly fast response!! Please let me know when you are able to create a release for this change.

**Comment by urish** [comment]
Sure thing!

**Comment by urish** [comment]
Released as 0.4.1

**Comment by benmarch** [comment]
Thanks, @urish!!

**Pull request merged**
